[package]
name = "pg"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7.13"
